### ISSUE TITLE
Tweens using callbacks?

### ISSUE THREAD

**Issue by bradparks** [kikito/tween.lua#11]
hey! I'm new to Lua, but was wondering if there's an easy way to get your tween library to just call a callback instead of applying the changes directly to a table? Perhaps the callback could have a few parameters, like:

percentComplete, delta

and percent = 0 is the start, and percent = 100 signifies the end of the tween, and returning false from the callback would cancel the tween?

I feel like I could mod the library to do this pretty easily, but was wondering what your thoughts were?

Thanks!

**Comment by kikito** [comment]
Hi there,

There are several reasons why I decided using tables instead of callbacks for tween.lua.

The main one has to do with that I really wanted it to be able to interpolate several properties simultaneously. If you give a look at the demo, you will see that a single tweener interpolates the color and the position of each "ball" simultaneously. In other words, I wanted tweeen to be able to transform something like this:
``` lua
{ x = 100, y = 200, color = {r=0, g=0, b=0} }
```
Into this:
``` lua
{ x = 300, y = 500, color = {r=125, g=255, b=50} }
```
With a single tween, and a single call to `update`.

> Perhaps the callback could have a few parameters, like:
> percentComplete, delta

You got that a bit wrong. In order to work like I said above, the callback doesn't need to know "how much time has passed". That's for the `update` method to figure out. What the callback needs is "what are the new values that I need on this frame".

If you are interpolating a single number, you would pass that number. Since I wanted tween to interpolate "whole structures", I would have to pass a table to the callback, It would look like this:

```lua
-- [...] are other parameters like start value, target value, time, etc.
local tweener = tween.new([...], function(t)
  -- do something with t.x, t.y, t.color.r, t.color.g & t.color.b
end)
```

An interesting question at this point is: how do I build `t`? There are basically two options: Either I build `t` again and again on every iteration (which is kind of slow) or I build `t` once and overwrite t again and again, which is faster (but a bit less "functionally pure").

The other interesting question is: what would people do with these callbacks? My (completely subjetive) suspicion is that most of the time people would use the callback to set the values in another table:

```lua
local player = {x = 100, y = 200, color = {r=0,g=0,b=0}}

local tweener = tween.new([...], function(t)
  player.x, player.y, player.color.r, player.color.g, player.color.b =
    t.x, t.y, t.color.r, t.color.g, t.color.b
end)
```
Once I saw this, I realized that If I build tween to automatically set the values in `player`, without using a callback, both questions would get resolved: I would have a "destination" table to override on every iteration, fast, and most of the library users would have to type less.

Of course this begs the question: what happens in the (few, in my opinion) scenarios where you can't use a table? There are several options here too, and fortunately Lua has an answer to each one. Here are a couple examples:

* If you are using "tables with methods" (so they must do `player:setX(x)` instead of `player.x = x`), you can either make the properties available in a "protected way" (`player._x = x`) or you can always use a "guard table" with a `__newindex` metamethod which calls `player:setX(x)` when `guard.x` is assigned `x`.
* If you only have a function to call (maybe to print something into a fileAw), you can use a table and call the function with the table right after calling update:
```lua
local tmp = {x = 100}
local tweener = tween.new(5, tmp, {x = 200})
...
tweener:update(dt)
myfunction(tmp) -- tmp now has the updated value
```

I hope this more or less answers your question. I will close this issue now, but feel free to reopen/comment if you need more guidance. Thanks for taking the time to open it in the first place!

**Comment by bradparks** [comment]
cool... thanks for the info... it makes it a bit clearer... thanks!
