### ISSUE TITLE
Two tweens played one after the other

### ISSUE THREAD

**Issue by Positive07** [kikito/tween.lua#14]
I have the following issue, I create all my tweens at startup like this:
```lua
local subject = { myVar = 0 }

local first  = tween.new(2, myVar, {myVar = 200})
local second = tween.new(2, myVar, {myVar = 400})

for i=1, 4 do
    local complete = first:update(dt)
    if complete then second:update(dt) end
   print(myVar)
end
```
I would expect:
```
100
200
300
400
```
But instead I get:
```
100
200
100
400
```
The problem is that since the tweens affect the same object and were created at the same time they always go back to the original state, when I just want them to "connect"

I know how the library works internally and that this is no simple change because you basically deepcopy the original table and use that as the base.

But for complex animations this is a needed feature, is this possible in a simple way?

Something like deepcopying the table on the first update of the tween

Note: Here I put two tweens but we are talking about many more, maybe a hundred, and most of them are repeated, modify really similar variables.

**Comment by kikito** [comment]
Hi!

I will think about your proposal - maybe we could wait to create the 'initial value' up until the first call to `:update` instead of doing it when the tween is created.

In the meantime, here's a code which will work with the current implementation (I had to fix several small bugs in your code first):
```lua
local tween = require 'tween'

local subject = { myVar = 0 }

local targets = { {myVar = 200}, {myVar = 400} }
local targetsIndex = 1
local t = tween.new(2, subject, targets[targetsIndex])
for i = 1, 4 do
  local complete = t:update(1)
  if complete then
    targetsIndex = (targetsIndex % #targets) + 1
    t = tween.new(2, subject, targets[targetsIndex])
  end
  print(subject.myVar)
end
```

I will keep this open so that I don't forget about this.

**Comment by Positive07** [comment]
Yes I have something like that right now, just wanted something simpler.

Thanks for considering this option

**Comment by kikito** [comment]
Hi there!

I have released a new version of tween which will work as you wanted. The change was easy to do and had little impact (all the tests passed on the first try, I just had to add a new one for the new scenario).

The code will not exactly as you wrote it when opening the issue, as there are several errors:

* Uses `myVar` instead of `subject` when creating the tweens
* Uses `dt` instead of `1` when updating the tweens
* The way `complete` is used, when the first tween finishes, the first step of the second tween is executed immediately (so it jumps from 100 to 300 instead of 200).
* Prints `myVar` instead of `subject.myVar` at the end

Here's the fixed code. It will work with the new version:

``` lua
local tween = require 'tween'

local subject = {myVar = 0}

local first  = tween.new(2, subject, {myVar = 200})
local second = tween.new(2, subject, {myVar = 400})

for i=1,4 do
  if complete then
    second:update(1)
  else
    complete = first:update(1)
  end
  print(subject.myVar)
end
```

It will print 100,200,300,400 as you initially expected.

Thanks for reporting this!
